apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-generator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lucasdamasceno96/devex-microservices-idp
    targetRevision: main
    path: platform/helm-chart
    helm:
      values: |
        image:
          repository: us-central1-docker.pkg.dev/ldp21k-labs/devex-idp/service-generator
          tag: latest
        replicaCount: 3
        environment:
          NODE_ENV: "production"
          LOG_LEVEL: "warn"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
