apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.14.4
    chart: external-secrets
    helm:
      values: |
        serviceAccount:
          annotations:
            iam.gke.io/gcp-service-account: devex-idp-ext-secrets@ldp21k-labs.iam.gserviceaccount.com
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
