apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lucasdamasceno96/devex-microservices-idp
    targetRevision: main
    path: gitops/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
